version 2.1
  job1:
    CicleCI-job:
      docker:
        - image: cimg/base:current
      steps:
        - checkout
        - run:
            name: "Say hello"
            command: "We need to meet today?"
  job2:
    CicleCI-job:
      docker:
        - image: cimg/base:current
      steps:
        - checkout
        - run:
            name: "Say hello"
            command: "Yeah?"
workflows:
  workflow1:
    jobs:
      - job1
      - job2